#!/bin/bash
. ./colorization.sh

echo ''
echo "${txtgrn}Ignore any errors produced by this... These are generated by packages not installed by pip2. Updating Python2 Packages...${txtrst}"
echo ''
a=`pip3 freeze | sed s/==// | sed s/[0-9][0-9]*//g | sed s/[.]//g`
for package in $a
do
  pip2 install $package --upgrade
  echo "${txtbld}${txtblu}----------${txtrst}"
done
echo ''
python --version
pip2 --version
echo ''
echo "${txtgrn}All done!${txtrst}"
exit
