#!/bin/bash
echo 'Ignore any errors produced by this... These are generated by packages not installed by pip3'
echo 'Updating Python3 Packages...'
echo ''
a=`pip3 freeze | sed s/==// | sed s/[0-9][0-9]*//g | sed s/[.]//g`
for package in $a
do
  pip3 install $package --upgrade
  echo '---------'
done
echo ''
python3 --version
pip3 --version
echo ''
echo 'All done!'
