#!/bin/bash
echo 'Ignore any errors produced by this... These are generated by packages not installed by pip2'
echo 'Updating Python2 Packages...'
echo ''
a=`pip3 freeze | sed s/==// | sed s/[0-9][0-9]*//g | sed s/[.]//g`
for package in $a
do
  pip2 install $package --upgrade
  echo '---------'
done
echo ''
python --version
pip --version
echo ''
echo 'All done!'
exit
